import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StoreProvider from "./StoreProvider";
import { SocketProvider } from "@/lib/hooks/socket/hooks";
import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import CustomAlert from "@/components/CustomAlert";
import { Provider } from "react-redux";
import { store } from "@/lib/store/store";
import { PersistGate } from "redux-persist/integration/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persister}>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Sidebar />
            <main>
              <Navbar />
              <CustomAlert />
              {children}
            </main>
          </body>
        </html>
      </PersistGate>
    </Provider>
  );
}
